MODEL_2D:
  TYPE: "SegFormer"
  DUAL_HEAD: True
  NUM_CLASSES: 16
  CKPT_PATH: "latte/exp/models/0310_nuscenes_usa_singapore_baseline_segformer_3/model_2d_100000.pth"
  SegFormer:
    backbone: "mit_b1"
    # pretrained_path: "latte/models/pretrained/segformer.b1.512x512.ade.160k.pth"
    decoder_cfg:
      feature_strides: [4, 8, 16, 32]
      in_channels: [64, 128, 320, 512]
      embedding_dim: 256
      dropout_rate: 0.1
    test_cfg:
      mode: 'slide'
      stride: (300, 300)
      crop_size: (450, 450)
MODEL_3D:
  TYPE: "SPVCNN"
  DUAL_HEAD: True
  NUM_CLASSES: 16
  CKPT_PATH: "latte/exp/models/0310_nuscenes_usa_singapore_baseline_segformer_3/model_3d_100000.pth"
  SPVCNN:
    cr: 1.0
HR_BLOCK:
  temp_wd_size: 3
  max_range: 40
  voxel_size: 0.3
  conf_perc: 0.75
CR_BLOCK:
  reduction: "mean"
  conf_mask: True
  ety_weight: True
DATASET_SOURCE:
  TYPE: "NuScenesSCN"
  TRAIN: ("train_usa",)
  VAL: ("val_usa",)
  NuScenesSCN:
    preprocess_dir: "latte/datasets/nuscenes/preprocess_all/preprocess"
    nuscenes_dir: "latte/datasets/nuscenes"  # only front cam images are needed
    resize: (800, 450)
    augmentation:
      bottom_crop: (450, 450)
    merge_classes: False
DATASET_TARGET:
  TYPE: "NuScenesSCN"
  TRAIN: ("train_singapore", "val_singapore", "test_singapore", )
  VAL: ("val_singapore", )
  TEST: ("train_singapore", "val_singapore", "test_singapore", )
  NuScenesSCN:
    preprocess_dir: "latte/datasets/nuscenes/preprocess_all/preprocess"
    nuscenes_dir: "latte/datasets/nuscenes"  # only front cam images are needed
    resize: (800, 450)
    augmentation:
      bottom_crop: (450, 450)
    merge_classes: False
DATALOADER:
  NUM_WORKERS: 4
OPTIMIZER:
  MODEL_2D:
    TYPE: "AdamW"
    BASE_LR: 0.0000006
    WEIGHT_DECAY: 0.01
    # AdamW:
    #   param_keys: ("pos_block", "norm", "head")
    #   mult_types: (["weight_decay",], ["weight_decay",], ["lr",])
    #   mults: (0.0, 0.0, 10)
  MODEL_3D:
    TYPE: "Adam"
    BASE_LR: 0.001
SCHEDULER:
  MODEL_2D:
    TYPE: "MultiStepLR"
    MultiStepLR:
      gamma: 0.1
      milestones: (80000, 90000)
  MODEL_3D:
    TYPE: "MultiStepLR"
    MultiStepLR:
      gamma: 0.1
      milestones: (80000, 90000)
  MAX_ITERATION: 100000
TRAIN:
  BATCH_SIZE: 6
  SUMMARY_PERIOD: 50
  CHECKPOINT_PERIOD: 5000
  UPDATE_PARAMS: "norm"
  RESET_DROPOUT: True
  LOG_PERIOD: 50
TTA:
  TYPE: "SAR"
  SAR:
    reset: True
VAL:
  BATCH_SIZE: 6
  PERIOD: 50
OUTPUT_DIR: "latte/exp/models"  #  @ will be replaced with config path, e.g. nuscenes/usa_singapore/xmuda
